# Generated by Django 3.2.12 on 2022-04-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=250)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(upload_to='portfolio/imagens')),
            ],
        ),
    ]
